version: '3.9'

services:
  postgrs:
    image: postgres:alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: "segments-db"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "123456"
    ports:
      - "15432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./assets/postgres/init.sql:/docker-entrypoint-initdb.d/1-schema.sql

volumes:
  pgdata: