env: "local"
http_server:
  address: "user-segmentation-service:8082"
  timout: 4s
  idle_tmout: 60s
postgresql:
  address: "postgres"
  port: 5432
  user: "postgres"
  password: "123456"
  db: "segments-db"